# Generated by Django 2.0.3 on 2018-11-06 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20181106_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='artist',
            new_name='artist_id',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='album',
            new_name='album_id',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='artist',
            new_name='artist_id',
        ),
    ]
